export {default as Login} from './auth/Login'
export {default as Signup} from './auth/Signup'
export {default as Client} from './client'
export {default as Clients} from './clients'
export {default as Dashboard} from './dashboard'
export {default as Employeer} from './employeer'
export {default as Students} from './students'
export {default as NotFound} from './NotFound'